In [4]:
import numpy as np
import matplotlib.pyplot as plt

c,s = 0.8, 0.6

r0 = np.array([[1, 0,0],[0, c, -s], [0, s, c]])
r1 = np.array([[c, 0,-s],[0, 1, 0], [s, 0, c]])

prod1 = r0 @ r1
prod2 = r1 @ r0

print("Prod1: \n", prod1)
print("Prod2: \n",prod2)

Prod1: 
 [[ 0.8   0.   -0.6 ]
 [-0.36  0.8  -0.48]
 [ 0.48  0.6   0.64]]
Prod2: 
 [[ 0.8  -0.36 -0.48]
 [ 0.    0.8  -0.6 ]
 [ 0.6   0.48  0.64]]
